name: rnaseq-meg-m1-ue5
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - hisat2    
    - samtools
    - trimmomatic

